INSERT INTO references_doc (name, category, type, description, usage, parameters, example) VALUES
('if', '控制', 'block', '条件判断积木块。当条件为真时执行内部的积木块。', '用于根据条件执行不同的代码逻辑。将条件放入菱形槽中，将要执行的积木块放入内部。', 'condition (boolean): 判断条件', 'if (score > 60) { showMessage("及格"); }'),
('if-else', '控制', 'block', '条件分支积木块。当条件为真时执行第一个分支，否则执行第二个分支。', '比 if 积木多了一个 else 分支，用于二选一的逻辑。', 'condition (boolean): 判断条件', 'if (age >= 18) { status = "成年"; } else { status = "未成年"; }'),
('repeat', '控制', 'block', '重复执行积木块。指定次数重复执行内部积木块。', '用于需要重复执行某些操作的场景，如循环添加列表项。', 'count (number): 重复次数', 'for (int i = 0; i < 10; i++) { list.add("Item " + i); }'),
('forever', '控制', 'block', '永远重复积木块。持续不断地执行内部积木块。', '常用于游戏循环或持续监听的场景。需要配合延时使用避免卡死。', '无参数', 'while (true) { updateGame(); delay(16); }'),
('wait', '控制', 'block', '等待积木块。暂停执行指定的毫秒数。', '用于在操作之间添加延时，如动画间隔、请求延迟等。', 'milliseconds (number): 等待毫秒数', 'Thread.sleep(1000); // 等待1秒'),
('toast', '控制', 'block', '显示 Toast 提示消息。', '在屏幕底部显示一条短暂的提示消息，常用于给用户反馈。', 'message (String): 提示内容', 'Toast.makeText(this, "保存成功", Toast.LENGTH_SHORT).show();'),
('finish', '控制', 'block', '关闭当前 Activity。', '结束当前页面并返回上一个页面。', '无参数', 'finish();'),

('setText', '操作', 'block', '设置 TextView 的文本内容。', '用于动态更改界面上文本控件显示的内容。', 'view (TextView): 目标控件\ntext (String): 要设置的文本', 'textview1.setText("Hello World");'),
('getText', '操作', 'block', '获取 EditText 的文本内容。', '读取用户在输入框中输入的文本。', 'view (EditText): 目标控件\n返回: String', 'String input = edittext1.getText().toString();'),
('setVisible', '操作', 'block', '设置控件的可见性。', '控制界面元素的显示和隐藏。', 'view (View): 目标控件\nvisibility (int): VISIBLE/INVISIBLE/GONE', 'button1.setVisibility(View.GONE);'),
('setEnabled', '操作', 'block', '设置控件是否可用。', '禁用或启用按钮等交互控件。', 'view (View): 目标控件\nenabled (boolean): 是否可用', 'button1.setEnabled(false);'),
('setImage', '操作', 'block', '设置 ImageView 的图片资源。', '用于动态更换图片控件显示的图片。', 'view (ImageView): 目标控件\nresource (String): 图片资源名', 'imageview1.setImageResource(R.drawable.icon);'),

('number', '变量', 'variable', 'Number 类型变量。存储整数或浮点数值。', '用于计数、计算、存储数值等场景。', '类型: double', 'double score = 0; score = score + 10;'),
('string', '变量', 'variable', 'String 类型变量。存储文本字符串。', '用于存储用户名、消息内容等文本数据。', '类型: String', 'String name = ""; name = edittext1.getText().toString();'),
('boolean', '变量', 'variable', 'Boolean 类型变量。存储真/假值。', '用于标记状态，如是否登录、是否显示等。', '类型: boolean', 'boolean isLoggedIn = false; isLoggedIn = true;'),
('list_string', '变量', 'variable', 'String 列表变量。存储字符串的有序集合。', '用于存储多个文本项，如聊天消息列表、菜单选项等。', '类型: ArrayList<String>', 'ArrayList<String> items = new ArrayList<>(); items.add("Apple");'),
('list_number', '变量', 'variable', 'Number 列表变量。存储数值的有序集合。', '用于存储分数、价格等数值数据的列表。', '类型: ArrayList<Double>', 'ArrayList<Double> scores = new ArrayList<>(); scores.add(95.5);'),
('map', '变量', 'variable', 'Map 变量。存储键值对数据。', '用于存储结构化数据，如用户信息（name->张三, age->18）。', '类型: HashMap<String, Object>', 'HashMap<String, Object> user = new HashMap<>(); user.put("name", "张三");'),

('Button', 'UI控件', 'widget', '按钮控件。用户可以点击触发操作。', '最常用的交互控件，通常配合 onClick 事件使用。', '常用属性: text, enabled, backgroundTint', 'button1.setText("提交"); button1.setOnClickListener(v -> submit());'),
('TextView', 'UI控件', 'widget', '文本显示控件。用于展示静态或动态文本。', '用于显示标题、描述、状态信息等。支持设置字体大小、颜色等。', '常用属性: text, textSize, textColor, gravity', 'textview1.setText("欢迎使用"); textview1.setTextSize(18);'),
('EditText', 'UI控件', 'widget', '文本输入控件。允许用户输入文本。', '用于表单输入，如用户名、密码、搜索框等。', '常用属性: hint, text, inputType, maxLines', 'String input = edittext1.getText().toString().trim();'),
('ImageView', 'UI控件', 'widget', '图片显示控件。用于展示图片资源。', '显示本地图片或网络图片。支持缩放模式设置。', '常用属性: src, scaleType, adjustViewBounds', 'imageview1.setImageResource(R.drawable.logo);'),
('LinearLayout', '布局', 'widget', '线性布局容器。子控件按水平或垂直方向排列。', '最基础的布局容器，支持 horizontal 和 vertical 两种方向。', '常用属性: orientation, gravity, weightSum', '// orientation="vertical" 垂直排列子控件'),
('ScrollView', '布局', 'widget', '滚动视图容器。当内容超出屏幕时可以滚动查看。', '包裹一个子布局，使其可以垂直滚动。只能有一个直接子控件。', '常用属性: fillViewport, scrollbars', '// 将 LinearLayout 放入 ScrollView 中实现长页面滚动'),
('ListView', 'UI控件', 'widget', '列表视图控件。以垂直滚动列表展示数据。', '配合 Adapter 使用，常用于展示聊天消息、设置项等列表数据。', '常用属性: divider, dividerHeight, listSelector', 'listview1.setAdapter(adapter); listview1.setOnItemClickListener(...);'),
('Spinner', 'UI控件', 'widget', '下拉选择控件。从预设选项中选择一个。', '用于性别选择、城市选择等有限选项的场景。', '常用属性: entries, prompt, spinnerMode', 'spinner1.setSelection(0); String selected = spinner1.getSelectedItem().toString();'),
('CheckBox', 'UI控件', 'widget', '复选框控件。可以选中或取消选中。', '用于多选场景，如同意协议、选择兴趣标签等。', '常用属性: checked, text', 'if (checkbox1.isChecked()) { agreeTerms = true; }'),
('Switch', 'UI控件', 'widget', '开关控件。在开/关两种状态间切换。', '用于设置页面的功能开关，如通知开关、暗黑模式等。', '常用属性: checked, text, thumbTint, trackTint', 'switch1.setOnCheckedChangeListener((v, checked) -> toggleDarkMode(checked));'),

('onClick', '点击事件', 'event', '当用户点击控件时触发。', '最常用的事件，通常绑定到 Button 上执行操作。', 'view (View): 被点击的控件', 'button1.setOnClickListener(v -> { /* 处理点击 */ });'),
('onLongClick', '点击事件', 'event', '当用户长按控件时触发。', '用于弹出上下文菜单或执行删除等操作。', 'view (View): 被长按的控件', 'view.setOnLongClickListener(v -> { showMenu(); return true; });'),
('onTextChanged', '文本事件', 'event', '当 EditText 中的文本发生变化时触发。', '用于实时搜索、输入验证、字符计数等场景。', 'text (CharSequence): 当前文本\nstart, before, count (int)', 'edittext1.addTextChangedListener(new TextWatcher() { ... });'),
('onItemSelected', '选择事件', 'event', '当 Spinner/ListView 的选项被选中时触发。', '用于响应用户的列表选择操作。', 'position (int): 选中位置\nitem (Object): 选中项', 'spinner1.setOnItemSelectedListener(new OnItemSelectedListener() { ... });'),
('onCheckedChanged', '状态事件', 'event', '当 CheckBox/Switch 的选中状态改变时触发。', '用于响应开关切换和复选框勾选操作。', 'isChecked (boolean): 是否选中', 'switch1.setOnCheckedChangeListener((v, checked) -> { ... });'),
('onBackPressed', '生命周期', 'event', '当用户按下返回键时触发。', '用于自定义返回行为，如显示退出确认对话框。', '无参数', 'onBackPressed() { showExitDialog(); }'),
('onCreate', '生命周期', 'event', 'Activity 创建时触发。', '初始化界面、设置数据、绑定事件的主要入口。', 'savedInstanceState (Bundle)', 'onCreate() { initViews(); loadData(); }'),

('SharedPreferences', '数据存储', 'component', '轻量级键值对存储组件。', '用于保存应用设置、用户偏好等小量数据。数据持久化存储在本地。', '常用方法: getString, putString, getInt, putInt, getBoolean', 'sp.edit().putString("username", name).apply(); String name = sp.getString("username", "");'),
('Intent', '系统组件', 'component', '意图组件。用于页面跳转和数据传递。', '在不同 Activity 之间导航和传递数据。也可用于调用系统功能。', '常用方法: putExtra, getStringExtra, setAction', 'Intent intent = new Intent(this, SecondActivity.class); intent.putExtra("id", 1); startActivity(intent);'),
('Timer', '工具组件', 'component', '定时器组件。按指定间隔重复执行任务。', '用于倒计时、轮播图自动切换、定时刷新数据等。', '常用方法: schedule, cancel\ndelay (long): 延迟毫秒\nperiod (long): 间隔毫秒', 'Timer timer = new Timer(); timer.schedule(task, 0, 1000);'),
('Dialog', 'UI组件', 'component', '对话框组件。显示模态对话框。', '用于确认操作、输入数据、选择选项等需要用户交互的场景。', '常用方法: setTitle, setMessage, setPositiveButton, show', 'new AlertDialog.Builder(this).setTitle("提示").setMessage("确定删除?").setPositiveButton("确定", ...).show();'),
('FilePicker', '系统组件', 'component', '文件选择器组件。让用户选择本地文件。', '用于选择图片、文档等文件进行上传或处理。', '常用方法: setType, launch\ntype (String): MIME 类型', 'Intent intent = new Intent(Intent.ACTION_GET_CONTENT); intent.setType("image/*"); startActivityForResult(intent, 1);'),
('Camera', '系统组件', 'component', '相机组件。调用系统相机拍照。', '用于拍照上传头像、扫描二维码等功能。', '常用方法: takePicture, onActivityResult', 'Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE); startActivityForResult(intent, 2);'),
('Vibrator', '系统组件', 'component', '振动器组件。控制设备振动。', '用于触觉反馈，如按钮点击振动、错误提示振动。', '常用方法: vibrate\nduration (long): 振动毫秒数', 'Vibrator v = (Vibrator) getSystemService(VIBRATOR_SERVICE); v.vibrate(200);'),
('MediaPlayer', '多媒体', 'component', '媒体播放器组件。播放音频文件。', '用于播放背景音乐、音效、录音等。', '常用方法: create, start, pause, stop, release', 'MediaPlayer mp = MediaPlayer.create(this, R.raw.sound); mp.start();');
